In [1]:
import numpy as np

a = np.random.rand(5)
print(a)

[0.94180248 0.95330096 0.52258344 0.22671    0.85594137]


In [11]:
print(a.shape) 
#rank 1 array
# never use rank 1 array 
# use either a column or row vector (use reshape to make sure) 

(5, 1)


In [4]:
print(a.T)

[0.94180248 0.95330096 0.52258344 0.22671    0.85594137]


In [6]:
print(np.dot(a,a.T))

2.852901145290035


In [7]:
a = np.random.rand(5,1)

In [8]:
print(a)

[[0.60846544]
 [0.56531736]
 [0.20826053]
 [0.89031553]
 [0.5884849 ]]


In [9]:
print(a.T)

[[0.60846544 0.56531736 0.20826053 0.89031553 0.5884849 ]]


In [10]:
print(np.dot(a,a.T))

[[0.37023019 0.34397607 0.12671933 0.54172623 0.35807272]
 [0.34397607 0.31958371 0.11773329 0.50331082 0.33268073]
 [0.12671933 0.11773329 0.04337245 0.18541758 0.12255818]
 [0.54172623 0.50331082 0.18541758 0.79266174 0.52393724]
 [0.35807272 0.33268073 0.12255818 0.52393724 0.34631448]]
